### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by nichtich** [mlawren/githook-perltidy#10]
pre-commit prints a lot of messages to STDOUT by default. I'd prefer no output unless something went wrong.

**Comment by mlawren** [comment]
On Mon Jun 25, 2018 at 12:10:17AM -0700, Jakob Voß wrote:
> pre-commit prints a lot of messages to STDOUT by default. I'd prefer
> no output unless something went wrong.

I mostly agree, except that I always want at least a notification or
message informing me that githook-perltidy is active: If I clone a repo
and forget to "githook-perltidy install" then I want to "see" that it
isn't there when committing.

I'm just in the middle now of cutting a new release that puts most of
the current output behind a --verbose flag. Once I see that the -TRIAL
release smokes well enough I'll do a full one.

Thanks for the feedback.

-- 
Mark Lawrence

**Comment by mlawren** [comment]
Test version 0.11.5_2 is much quieter by default and now on CPAN. A new stable version will follow shortly.
