### ISSUE TITLE
pre-commit support

### ISSUE THREAD

**Issue by mapshen** [mlawren/githook-perltidy#11]
It would be great if this is supported by [pre-commit](https://pre-commit.com/hooks.html). Can we make this happen?

**Comment by mlawren** [comment]
On Fri Jul 13, 2018 at 11:44:29AM -0700, mapshen wrote:
> It would be great if this is support by
> [pre-commit](https://pre-commit.com/hooks.html). Can we make this
> happen?

I'm not against it in principle, but I struggle a bit to understand
what the requirements are from a plugin point of view. Do I just need
to create a .pre-commit-hooks.yaml file in this repo?

I'm happy to work with you if you are happy to do most of the work, but
I don't have the motivation to investigate and test pre-commit myself
at this stage.

-- 
Mark Lawrence

**Comment by mlawren** [comment]
Ah, your approach with perltidy directly makes more sense to me now in the context of the pre-commit tool. Pre-commit and githook-perltidy overlap to a certain degree and probably wouldn't integrate well.
