### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by nfg** [mlawren/githook-perltidy#14]
Hello!

I have a setup script at $WORK that installs this githook. One of my coworkers ran it last week, and it ran into the issue where it fails against the new release of OptArg2. I see you're the owner of both packages, and it looks like you've fixed it already in master. Do you have any idea when you're going to release an updated version of the githook?

Thanks for all your work, eh. I've gotten a lot of value out of this tool. 😀

**Comment by mlawren** [comment]
Hi, it's always good for the ego to hear that one is providing value - thanks!

The possibility of this issue occurring had been bugging me a bit. I was waiting on cpantesters to come up with some results but it seems 1.0.0_2 somehow got ignored by them. Anyway, I've taken the leap and just put 1.0.0 out now.

**Comment by nfg** [comment]
Woohoo! Thank you! 🎉
