### ISSUE TITLE
Perl::Critic support

### ISSUE THREAD

**Issue by campadrenalin** [mlawren/githook-perltidy#5]
It would be great if this was capable of running perlcritic the same way it does perltidy (i.e., only on files being committed). While this is not an immediate need, it would be very nice to have, and I'm actually open to implementing it myself, given a bit of guidance on how best to do it.

**Comment by icydee** [comment]
I am willing to give this a go, but I note that you have version 11.1_5 available (as a developer release) but only 11.1_4 available here on github?

I have cloned your repo, but where would I get 11.1_5 on git please?

**Comment by mlawren** [comment]
Ok, took me a few cycles but I now see I hadn't pushed the last two commits. Github should be up to date now. I look forward to receiving a pull request!

**Comment by mlawren** [comment]
Support for Perl::Critic was implemented in the just-released version 0.11.11_2. As soon as I see success reports from CPAN testers I'll release a stable version.

Thanks for the suggestion.
