### ISSUE TITLE
Get it to recognize .cgi files

### ISSUE THREAD

**Issue by Klortho** [mlawren/githook-perltidy#6]
It seems you have hardcoded the recognized extensions ([here](https://github.com/mlawren/githook-perltidy/blob/devel/lib/App/githook_perltidy/pre_commit.pm#L45), for example). It would be nice if those could be passed in as a command-line option, so that, for example, I could add ".cgi".

**Comment by dolmen** [comment]
If `.cgi` is added, `.psgi` should be added too.

**Comment by Klortho** [comment]
That's why I suggested making it configurable. I guess it could be added as an option to `githook-perltidy install`, which would then have to store the information somewhere (not sure where).

**Comment by mlawren** [comment]
On Wed Jan 06, 2016 at 09:38:55AM -0800, Chris Maloney wrote:

> It seems you have hardcoded the recognized extensions
> ([here](https://github.com/mlawren/githook-perltidy/blob/devel/lib/App/githook_perltidy/pre_commit.pm#L45),
> for example). It would be nice if those could be passed in as a
> command-line option, so that, for example, I could add ".cgi".

Those extensions are only a shortcut. Another test is made a couple of
lines further down:

    next
      unless $possible =~ m/^#!.*perl/
      or $possible =~ m/^#!.*\.plenv/;

Do Perl .cgi or .psgi files typically have a hashbang first line? If
they did I would expect them to be picked up already. The file
bin/githook-perltidy itself has a #!perl in place for this reason.

On Fri Jan 08, 2016 at 01:23:30PM -0800, Chris Maloney wrote:
> That's why I suggested making it configurable. I guess it could be
> added as an option to `githook-perltidy install`, which would then
> have to store the information somewhere (not sure where).

I'm not against making the shortcut list configurable. However I don't
have the tuits myself to implement and document and test that based on
two requests in five years... sorry.

Let me know if the #!perl thing isn't sufficient for either of you and
we can discuss more about adding .cgi and .psgi. My only concern is
files called .cgi that aren't written in Perl. I guess I took a
(acceptable in my opinion) risk with the first \.(pl|pod|pm|t) match.

Perhaps the code above could be extended to look for /^use.*;/ or some
other common Perl...

Cheers,
Mark
-- 
Mark Lawrence

**Comment by mlawren** [comment]
Woops - I also see that I only had a decent/working #!perl check in my local development version. So I've just released 0.11.2 with up to date changes which may work differently (better) for you now.

**Comment by Klortho** [comment]
Yes, that works -- thanks!
